app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', [
    'uses' => '\Prego\Http\Controllers\HomeController@index',
    'as'   => 'index'
]);

/**
 *  Authentication routes
 */
Route::get('/auth/register', [
    'uses' => '\Prego\Http\Controllers\AuthController@getRegister',
    'as'   => 'auth.register',
    'middleware' => ['guest']
]);

Route::post('/auth/register', [
    'uses' => '\Prego\Http\Controllers\AuthController@postRegister',
    'middleware' => ['guest']
]);

Route::get('/auth/signin', [
    'uses' => '\Prego\Http\Controllers\AuthController@getLogin',
    'as'   => 'auth.login',
    'middleware' => ['guest']
]);

Route::post('/auth/signin', [
    'uses' => '\Prego\Http\Controllers\AuthController@postLogIn',
    'middleware' => ['guest']
]);

Route::get('/logout', [
    'uses' => '\Prego\Http\Controllers\AuthController@logOut',
    'as'   => 'auth.logout'
]);

Route::resource('projects', 'ProjectController');

# Comment routes
Route::post('projects/{projects}/comments', [
    'uses' => 'ProjectCommentsController@postNewComment',
    'as'   => 'projects.comments.create',
    'middleware' => ['auth']
]);

Route::get('projects/{projects}/comments/{comments}/edit', [
    'uses' => 'ProjectCommentsController@getOneProjectComment',
    'as' => 'projects.comments'
]);

Route::put('projects/{projects}/comments/{comments}', [
    'uses' => 'ProjectCommentsController@updateOneProjectComment',
]);

Route::delete('projects/{projects}/comments/{comments}', [
    'uses' => 'ProjectCommentsController@deleteOneProjectComment',
]);

# Collaborator routes
Route::post('projects/{projects}/collaborators', [
    'uses' => 'ProjectCollaboratorsController@addCollaborator',
    'as'   => 'projects.collaborators.create',
    'middleware' => ['auth']
]);

Route::delete('projects/{projects}/collaborators/{collaborators}', [
    'uses' => 'ProjectCollaboratorsController@deleteOneCollaborator',
]);

# Task routes
Route::post('projects/{projects}/tasks', [
    'uses' => '\Prego\Http\Controllers\ProjectTasksController@postNewTask',
    'as' => 'projects.tasks.create'
]);

Route::get('projects/{projects}/tasks/{tasks}/edit', [
    'uses' => '\Prego\Http\Controllers\ProjectTasksController@getOneProjectTask',
    'as' => 'projects.tasks'
]);

Route::put('projects/{projects}/tasks/{tasks}', [
    'uses' => '\Prego\Http\Controllers\ProjectTasksController@updateOneProjectTask',
]);

Route::delete('projects/{projects}/tasks/{tasks}', [
    'uses' => '\Prego\Http\Controllers\ProjectTasksController@deleteOneProjectTask',
]);

Route::post('projects/{projects}/files', [
     'uses' => '\Prego\Http\Controllers\FilesController@uploadAttachments',
     'as'   => 'projects.files',
     'middleware' => ['auth']
]);

app/Project.php
<?php

namespace Prego;

use Auth;
use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['project_name', 'project_notes', 'project_status', 'due_date'];

    public function scopePersonal($query)
    {
        return $query->where('user_id', Auth::user()->id);
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace Prego\Http\Controllers;

use Illuminate\Http\Request;

use Auth;
use Prego\File;
use Prego\Task;
use Prego\Comment;
use Prego\Project;
use Prego\Collaboration;
use Prego\Http\Requests;
use Prego\Http\Controllers\Controller;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $projects = Project::personal()->get();
        return view('projects.index')->withProject($projects);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('projects.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'     => 'required|min:3',
            'due-date' => 'required|date|after:today',
            'notes'    => 'required|min:10',
            'status'   => 'required'
        ]);

        $project = new Project;
        $project->project_name   = $request->input('name');
        $project->project_status = $request->input('status');
        $project->due_date       = $request->input('due-date');
        $project->project_notes  = $request->input('notes');
        $project->user_id        = Auth::user()->id;

        $project->save();

        return redirect()->route('projects.index')->with('info','Your Project has been created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $project       = Project::find($id);
        $tasks         = $this->getTasks($id);
        $files         = $this->getFiles($id);
        $comments      = $this->getComments($id);
        $collaborators = $this->getCollaborators($id);
        return view('projects.show')
                            ->withProject($project)
                            ->withTasks($tasks)
                            ->withFiles($files)
                            ->withComments($comments)
                            ->withCollaborators($collaborators);
    }

    /**
     * Get all the tasks that belongs to a project
     * @param  integer $id
     * @return collection
     */
    public function getTasks($id)
    {
        $tasks =  Task::project($id)->get();
        return $tasks;
    }

    /**
     * Get all the files that were attached to a project
     * @param  integer $id
     * @return collection
     */
    public function getFiles($id)
    {
        $files =  File::project($id)->get();
        return $files;
    }

    /**
     * Get all the comments that were made on a Project
     * @param  integer $id
     * @return collection
     */
    public function getComments($id)
    {
        $comments = Comment::project($id)->get();
        return $comments;
    }

    /**
     * Get all the collaborators on this project
     * @param  int $id
     * @return collection
     */
    public function getCollaborators($id)
    {
        $collaborators = Collaboration::project($id)->get();
        return $collaborators;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $project = Project::find($id);
        return view('projects.edit')->withProject($project);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $project = Project::findOrFail($id);

        $this->validate($request, [
            'project_name'     => 'required|min:3',
            'due-date'         => 'required|date|after:today',
            'project_notes'    => 'required|min:10',
            'project_status'   => 'required'
        ]);

        $values = $request->all();
        $project->fill($values)->save();

        return redirect()->back()->with('info','Your Project has been updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $project = Project::findOrFail($id);
        $project->delete();

        return redirect()->route('projects.index')->with('info', 'Project deleted successfully');
    }
}

resources/views/projects/edit.blade.php
@extends('layouts.master')

@section('content')

@include('layouts.partials.sidebar')
 <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header"> Edit Project</h1>

    @include('layouts.partials.alerts')
    <div class="col-lg-6">
        <form class="form-vertical" role="form" method="post" action="{{ route('projects.update', $project->id) }}">
            <div class="form-group{{ $errors->has('project_status') ? ' has-error' : '' }}">
                <label for="status" class="control-label">Choose Status</label>
                <select name="project_status" id="status">
                    <option value="{!! $project->project_status !!}">{!! $project->project_status !!}</option>
                    {{ getStatus($project->project_status) }}
                </select>
                @if ($errors->has('project_status'))
                    <span class="help-block">{{ $errors->first('project_status') }}</span>
                @endif
            </div>
            <div class="form-group{{ $errors->has('project_name') ? ' has-error' : '' }}">
                <label for="name" class="control-label">Name</label>
                <input type="text" name="project_name" class="form-control" id="name" value="{!! $project->project_name ?: '' !!}">
                @if ($errors->has('project_name'))
                    <span class="help-block">{{ $errors->first('project_name') }}</span>
                @endif
            </div>
            <div class="form-group{{ $errors->has('due-date') ? ' has-error' : '' }}">
                <label for="due-date" class="control-label">Due date</label>
                <input type="date" name="due-date" class="form-control" id="due-date" value="{!! $project->due_date !!}">
                @if ($errors->has('due-date'))
                    <span class="help-block">{{ $errors->first('due-date') }}</span>
                @endif
            </div>
            <div class="form-group{{ $errors->has('project_notes') ? ' has-error' : '' }}">
                <label for="notes" class="control-label">Notes</label>
                <textarea name="project_notes" class="form-control" id="notes" rows="10" cols="10">{!! trim($project->project_notes) !!}</textarea>
                @if ($errors->has('project_notes'))
                    <span class="help-block">{{ $errors->first('project_notes') }}</span>
                @endif
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-info">Update</button>
            </div>
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            {!! method_field('PUT') !!}
        </form>
    </div>
</div>
@stop

resources/views/projects/index.blade.php
@extends('layouts.master')

@section('content')

@include('layouts.partials.sidebar')
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    @include('layouts.partials.alerts')
    <h1 class="page-header">
        Projects
        <a class="btn btn-info" href="{{ route('projects.create') }}">New Project</a>
    </h1>

    <div class="container">
        @if( $project )
            <div class="row">
                @foreach ($project as $proj)
                    <div class="col-md-3" style="border:1px solid #ccc;margin-left:5px;">
                      <h2><a href="/projects/{{ $proj->id }}">{!! $proj->project_name !!}</a></h2>
                      <p>Due : {!! date_format(new DateTime($proj->due_date), "D, m Y") !!}</p>
                      <p>Status: {!! $proj->project_status !!}</p>
                      <p>Tasks: 0</p>
                      <p>Comments: 0</p>
                      <p>Attachments: 0</p>
                    </div>
                @endforeach
            </div>
        @endif
    </div>

    @if( $project->isEmpty() )
       <h3>There are currently no Projects</h3>
    @endif
</div>
@stop

resources/views/projects/new.blade.php
@extends('layouts.master')

@section('content')

@include('layouts.partials.sidebar')
 <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">New Project</h1>

    <div class="col-lg-6">
        <form class="form-vertical" role="form" method="post" action="{{ route('projects.store') }}">
            <div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
                <label for="status" class="control-label">Choose Status</label>
                <select name="status" id="status">
                    <option value="">Choose a status</option>
                    <option value="Upcoming">Upcoming</option>
                    <option value="Active">Active</option>
                    <option value="Completed">Completed</option>
                </select>
                @if ($errors->has('status'))
                    <span class="help-block">{{ $errors->first('status') }}</span>
                @endif
            </div>
            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                <label for="name" class="control-label">Name</label>
                <input type="text" name="name" class="form-control" id="name" value="{{ old('name') ?: '' }}">
                @if ($errors->has('name'))
                    <span class="help-block">{{ $errors->first('name') }}</span>
                @endif
            </div>
            <div class="form-group{{ $errors->has('due-date') ? ' has-error' : '' }}">
                <label for="due-date" class="control-label">Due date</label>
                <input type="date" name="due-date" class="form-control" id="due-date">
                @if ($errors->has('due-date'))
                    <span class="help-block">{{ $errors->first('due-date') }}</span>
                @endif
            </div>
            <div class="form-group{{ $errors->has('notes') ? ' has-error' : '' }}">
                <label for="notes" class="control-label">Notes</label>
                <textarea name="notes" class="form-control" id="notes" rows="10" cols="10">
                    {{ old('notes') ?: '' }}
                </textarea>
                @if ($errors->has('notes'))
                    <span class="help-block">{{ $errors->first('notes') }}</span>
                @endif
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Create</button>
            </div>
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
        </form>
    </div>
</div>
@stop

resources/views/projects/show.blade.php
@extends('layouts.master')

@section('content')

@include('layouts.partials.sidebar')
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    @include('layouts.partials.alerts')
    @if( $project )
    <h1 class="page-header">
        {!! $project->project_name !!}
    </h1>

    <div class="container">
        <div class="row">
            <div class="col-md-3" style="border:1px solid #ccc;margin-left:5px;padding:10px;">
              <p>Due : {!! date_format(new DateTime($project->due_date), "D, m Y") !!}</p>
              <p>Status: {!! $project->project_status !!}</p>
              <p>Tasks: {{ count($tasks) }} </p>
              <p>Comments: {{ count($comments) }}</p>
              <p>Attachments: {{ count($files) }} </p>
              <p><a href="/projects/{{ $project->id }}/edit">Edit</a></p>
                  <button class="btn btn-circle btn-danger delete"
                          data-action="{{ url('projects/' . $project->id) }}"
                          data-token="{{csrf_token()}}">
                    <i class="fa fa-trash-o"></i>Delete
                  </button>
            </div>
            @include('collaborators.form')
        </div>
        <hr>
        <div class="row">
            @include('tasks.form')
            @include('files.form')
        </div>
        <hr>
        <div class="row">
            @include('comments.form')
        </div>
    </div>
    @endif
</div>
@stop